const items=[
{id:1,name:'燻製ミックスナッツ',category:'おつまみ',price:680,amount:'80g',code:'Smoked.',tint:'#f6e4d2',desc:'香ばしさのあとに、ふわりと燻製の余韻。',detail:'アーモンド・カシューナッツ・くるみの架空のミックス。少しずつつまみたい夜に。'},
{id:2,name:'黒胡椒のチーズ',category:'チーズ',price:780,amount:'100g',code:'Cheese.',tint:'#f8edb7',desc:'まろやかなチーズに、黒胡椒をきかせて。',detail:'コクのあるチーズと黒胡椒を組み合わせた架空の商品。パンと一緒にも。'},
{id:3,name:'ハーブ香るオリーブ',category:'おつまみ',price:620,amount:'120g',code:'Olive.',tint:'#dfe9da',desc:'さっぱりとした酸味と、ハーブの香り。',detail:'グリーンオリーブをハーブ風味で仕上げた架空の商品。そのまま小皿に盛るだけ。'},
{id:4,name:'海老のアヒージョ',category:'ごちそう',price:980,amount:'150g',code:'Ajillo.',tint:'#f6d8ce',desc:'にんにく香るオイルまで、パンとどうぞ。',detail:'海老とマッシュルームの架空のアヒージョ。週末の食卓に、温かいひと皿を。'},
{id:5,name:'とろける生チョコ',category:'甘いもの',price:850,amount:'9粒',code:'Cacao.',tint:'#e8dcd6',desc:'一日のしめくくりに、ほろ苦いごほうび。',detail:'カカオの香りを楽しむ架空の生チョコレート。コーヒーと一緒にゆっくりと。'},
{id:6,name:'きのこの濃厚パテ',category:'ごちそう',price:720,amount:'90g',code:'Pâté.',tint:'#e0e5ed',desc:'ひと塗りで、いつものパンがごちそうに。',detail:'きのこの旨みを詰め込んだ架空のパテ。クラッカーやトーストに添えて。'}];
const cart=new Map();let category='すべて';let timer;const $=id=>document.getElementById(id);const yen=n=>'¥'+n.toLocaleString('ja-JP');const modal=$('modal');
function render(){const q=$('search').value.trim();const list=items.filter(p=>(category==='すべて'||p.category===category)&&[p.name,p.category,p.desc].some(v=>v.includes(q)));$('resultCount').textContent=list.length+'点の商品';$('filters').innerHTML=['すべて','おつまみ','チーズ','ごちそう','甘いもの'].map(c=>`<button data-category="${c}" class="${category===c?'active':''}" aria-pressed="${category===c}">${c}</button>`).join('');$('products').innerHTML=list.length?list.map(p=>`<article class="product"><button class="product-top" style="--tint:${p.tint}" data-detail="${p.id}" aria-label="${p.name}の詳細"><span class="tag">${p.category}</span><span class="product-code">${p.code}</span></button><div class="product-body"><button class="product-title" data-detail="${p.id}">${p.name}</button><p>${p.desc}<br>${p.amount}</p><div class="product-bottom"><span class="price">${yen(p.price)}</span><button class="add" data-add="${p.id}">カートに追加</button></div></div></article>`).join(''):'<p class="empty">該当する商品がありません。<br>検索語やカテゴリを変えてみてください。</p>';}
function notify(msg){$('toast').textContent=msg;$('toast').classList.add('show');clearTimeout(timer);timer=setTimeout(()=>$('toast').classList.remove('show'),2400)}
function count(){return [...cart.values()].reduce((a,b)=>a+b,0)}function total(){return items.reduce((s,p)=>s+p.price*(cart.get(p.id)||0),0)}function updateCount(){$('count').textContent=count()}
function add(id){cart.set(id,(cart.get(id)||0)+1);updateCount();notify('カートに追加しました')}
function open(title,html){$('modalTitle').textContent=title;$('modalBody').innerHTML=html;if(!modal.open)modal.showModal()}
function summary(){return `<div class="total-line"><span>商品小計（税込）</span><strong>${yen(total())}</strong></div><div class="total-line"><span>送料（デモ）</span><span>¥0</span></div><div class="total-line"><strong>合計</strong><strong>${yen(total())}</strong></div>`}
function showCart(){open('カート ('+count()+'点)',cart.size?items.filter(p=>cart.has(p.id)).map(p=>`<div class="cart-row"><div class="cart-row-top"><strong>${p.name}</strong><span>${yen(p.price*cart.get(p.id))}</span></div><div class="quantity"><button data-change="${p.id}" data-delta="-1" aria-label="${p.name}を1点減らす">−</button><span>${cart.get(p.id)}</span><button data-change="${p.id}" data-delta="1" aria-label="${p.name}を1点増やす">＋</button><button class="remove" data-remove="${p.id}">削除</button></div></div>`).join('')+summary()+'<button class="primary" id="checkout">購入画面へ進む</button><button class="secondary" data-close>買い物を続ける</button>':'<p class="notice">カートは空です。気になる商品を追加してみましょう。</p><button class="primary" data-close>商品を見る</button>')}
function checkout(){if(!cart.size)return showCart();open('ご注文内容の確認',`<p class="notice">購入体験のデモです。住所・カード番号の入力は不要です。実際の注文、配送、請求は行われません。</p>${items.filter(p=>cart.has(p.id)).map(p=>`<div class="total-line"><span>${p.name} × ${cart.get(p.id)}</span><span>${yen(p.price*cart.get(p.id))}</span></div>`).join('')}${summary()}<button class="primary" id="complete">デモ注文を確定する</button><button class="secondary" id="backCart">カートに戻る</button>`)}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.category){category=b.dataset.category;render()}if(b.dataset.add)add(Number(b.dataset.add));if(b.dataset.detail){const p=items.find(x=>x.id===Number(b.dataset.detail));open(p.name,`<div class="detail-code" style="background:${p.tint}">${p.code}</div><p class="detail-text">${p.detail}</p><p>${p.amount} · ${yen(p.price)}（税込）</p><p class="muted">デモ商品です。販売・配送は行いません。</p><button class="primary" data-add="${p.id}">カートに追加</button>`)}if(b.dataset.change){const id=Number(b.dataset.change),n=(cart.get(id)||0)+Number(b.dataset.delta);if(n<=0)cart.delete(id);else cart.set(id,n);updateCount();showCart()}if(b.dataset.remove){cart.delete(Number(b.dataset.remove));updateCount();showCart()}if(b.id==='cartButton'||b.id==='backCart')showCart();if(b.id==='checkout')checkout();if(b.id==='closeModal'||b.hasAttribute('data-close'))modal.close();if(b.id==='complete'&&cart.size){cart.clear();updateCount();open('デモ注文が完了しました','<div class="success"><strong>ひとくち、ありがとう。</strong><p>商品選びから購入完了まで体験できました。<br>実際の決済・配送は発生しません。</p></div><button class="primary" data-close>ショップに戻る</button>')}});
$('search').addEventListener('input',render);modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)modal.close()}});render();
